drm/amd/dal: Fix building with C++ compiler.
Move struct definitions outside anonymous unions.  Without this,
including these files from a C++ source file causes an error from g++:

../../include/audio_types.h:134:10: error: ‘struct
audio_info_flags::<anonymous union>::audio_speaker_flags’ invalid; an
anonymous union can only have non-static data members [-fpermissive]

Signed-off-by: Ken Chalmers <ken.chalmers@amd.com>
Acked-by: Harry Wentland <harry.wentland@amd.com>